---
parser: babel-eslint
extends:
- eslint:recommended
- plugin:import/errors
- plugin:import/warnings
plugins:
- import
settings:
  import/parser: babel-eslint
  import/resolver:
    node:
      extensions:
      - ".js"
      moduleDirectory:
      - "./js"
      - "./node_modules"
    webpack:
      config: webpack.web.config.js
      config-index: 0
env:
  browser: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
ecmaFeatures:
  classes: true
  modules: true
rules:
  quotes:
  - error
  - backtick
  semi:
  - error
  - always
  indent:
  - error
  - 2
  - SwitchCase: 1
  block-spacing: error
  brace-style:
  - error
  - 1tbs
  - allowSingleLine: true
  comma-spacing:
  - error
  - before: false
    after: true
  no-unused-vars:
  - 1
  - vars: local
    args: none
  no-console:
  - error
  - allow:
    - info
    - warn
  no-nested-ternary: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  import/no-unresolved: 2
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
